# https://github.com/Azure/container-scan#ignoring-vulnerabilities
general:
  vulnerabilities:
    - CVE-2023-31484
    - CVE-2023-45853
    - CVE-2023-50387
    - CVE-2023-50868
#  bestPracticeViolations:
#    - CIS-DI-0001
#    - DKL-DI-0006
#    - CIS-DI-0006
#    - CIS-DI-0008
